# Generated by Django 3.2.5 on 2021-07-08 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_name', models.CharField(max_length=100)),
                ('query_id', models.PositiveSmallIntegerField(default=0)),
                ('num_fake', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.CharField(default='0.0.0.0', max_length=50)),
                ('browser', models.CharField(default='None', max_length=70)),
                ('curr_q', models.PositiveSmallIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('order', models.CharField(default='1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='TopScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('username', models.CharField(default='anonymous', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_elapsed', models.PositiveSmallIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('chosen_alg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chosen', to='version2.algorithm')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version2.query')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version2.respondent')),
                ('unchosen_alg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unchosen', to='version2.algorithm')),
            ],
        ),
    ]
